### ISSUE TITLE
Update to redux-persist v5

### ISSUE THREAD

**Issue by outaTiME** [maxdeviant/redux-persist-transform-encrypt#18]
Hi, it will awesome to support de v5 of redux-persist.

Thanks !!!

**Comment by nikhil4326** [comment]
Is there any other way to encrypt redux state? 
is someone maintaining this library?

**Comment by maxdeviant** [comment]
I'll look into getting this upgraded to `redux-persist` v5.

PRs always welcome :wink:

**Comment by nikhil4326** [comment]
Hey I have used same version with redux persist V5. that is working fine.
only difference is in implementation.
I dont know that is correct way or not . If you want i will post here.

**Comment by rt2zz** [comment]
This lib should support v5 just fine, I think just need to update the readme to put transforms on persistReducer instead of persistStore

**Comment by nikhil4326** [comment]
correct. Somethimg like.

```
//config object with encryptor info
//key: localstorage key, storage: default is localstorage.
const configPersist = {
  key: 'root',
  storage,
  transforms: [encryptor]
}

const reducer = persistReducer(configPersist, Reducers)
```

check [issue](https://github.com/rt2zz/redux-persist/issues/545) raised redux-persit forum by me.

**Comment by maxdeviant** [comment]
I should have some time to look into this tonight.

**Comment by maxdeviant** [comment]
Support for `redux-persist@5` has been added in [v2.0.0](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v2.0.0).

Just needed to update the `peerDependencies` and examples.
