### ISSUE TITLE
Add configurable error handling/logging system

### ISSUE THREAD

**Issue by maxdeviant** [maxdeviant/redux-persist-transform-encrypt#19]
Currently we just call `console.(log|info|warn|error)` to report issues back to the user.

We should be able to pass in a custom error handler/logger that is configurable by the library consumer so usage is more flexible.

**Comment by ekynoxe** [comment]
Hi @maxdeviant I had a first go at this. It's super simple for now, to get the ball rolling.
Let me know what you think about https://github.com/maxdeviant/redux-persist-transform-encrypt/pull/20

**Comment by ekynoxe** [comment]
Thanks for merging #20, @maxdeviant Does this mean this issue can be closed?
I'm still (shame on me) unfamiliar with how versions are being published to npm, so I'll be waiting for that before I upgrade the application using redux-persist-transform-encrypt. At least I can reference a `master` commit! Thanks!

**Comment by maxdeviant** [comment]
@ekynoxe I haven't published a new version to npm yet. I wanted to document the error handler feature first.

**Comment by ekynoxe** [comment]
Hi @maxdeviant I've added docs and a few things around tests in #25 Can you let me know if more is needed in order to create a new release? I'd really like to use a proper version in our package dependencies.

**Comment by maxdeviant** [comment]
@ekynoxe This is available in `v2.0.1`. Thanks for the help!

**Comment by ekynoxe** [comment]
Fantastic, @maxdeviant Thanks a lot!
