### ISSUE TITLE
sync vs async

### ISSUE THREAD

**Issue by sibelius** [maxdeviant/redux-persist-transform-encrypt#23]
what are the differences of sync and async method?

both of them work on react-native?

**Comment by maxdeviant** [comment]
@sibelius I'm not all too familiar with the async methodology, it was added in a PR by another contributor. It's still not really finalized/supported, I just haven't had the time to look into it further.

The difference between the two is that async runs the encryption/decryption asynchronously which could provide better performance.

Sync should work fine on React Native, and async may or may not work.

**Comment by sibelius** [comment]
tks for the explanation, I'll try to make this work with react-native

this is a great package, tks
