### ISSUE TITLE
Issue with REHYDRATE 

### ISSUE THREAD

**Issue by lalitaphalak** [maxdeviant/redux-persist-transform-encrypt#26]
I am using "redux-persist": "4.10.2", "redux-persist-transform-encrypt": "1.0.2" in my project.

I have recently added "redux-persist-transform-encrypt" to project. And getting issue when I try to refresh page in browser.

I have customized REHYDRATE action and was getting all of my reducers in action.payload in reducer. By using that values I used to perform some customizations. But after integrating "redux-persist-transform-encrypt" I found that reducer value is coming out to be null. 

And if I use ayncEncryptor, for each reducer I am getting {"" : random_number}.

Otherwise encryption, decryption is working as expected.

**Comment by maxdeviant** [comment]
Closing due to age.

We can reopen this issue if the problem still exists with the latest versions of `redux-persist-transform-encrypt` and `redux-persist`.
