### ISSUE TITLE
Missing es2015, caused by .babelrc

### ISSUE THREAD

**Issue by robmoorman** [maxdeviant/redux-persist-transform-encrypt#3]
Using this module in React Native causes the packager to throw a transform error (couldn't find preset es2015).
A solution would be to add a . npmignore file were this .babelrc file is ignored, either way a improvement to exclude unnecessary files when installing this module with NPN.

**Comment by rt2zz** [comment]
👍 

I think whitelisting files in package.json is the way to go. PR will be gladly merged!

**Comment by maxdeviant** [comment]
This should be fixed in v0.1.1.
