### ISSUE TITLE
Required key

### ISSUE THREAD

**Issue by Sphinxs** [maxdeviant/redux-persist-transform-encrypt#32]
Do I really need to pass `scretKey` and `key` ? If I don't pass `key` in `persistReducer` I receive an error (*Error : key is required in persistor config*) ...

```javascript
const reducers = combineReducers({
  ...
});

const middlewares = applyMiddleware(error, thunk);

const encryptor = createEncryptor({
  secretKey: 'portfolio',
  onError: error => {
    // Handle the error
  }
})

const persistedReducer = persistReducer(
  {
    key: 'portfolio',
    storage,
    transforms: [encryptor]
  },
  reducers
);

const store = createStore(
  persistedReducer,
  initialState,
  middlewares,
  window.devToolsExtension && window.devToolsExtension()
);

const persistor = persistStore(store);
```

**Comment by maxdeviant** [comment]
@Sphinxs `secretKey` is required by `redux-persist-transform-encrypt` in order to securely encrypt the state.

`key` is required by `redux-persist` to tell it which keys in the store should be persisted.

Hope that helps clarify it for you.

**Comment by Sphinxs** [comment]
Yes, thanks ( :

**Comment by Sajjad1432** [comment]
Hey  folks , can anybody help me i am facing same issue
