### ISSUE TITLE
Encrypt already stored unencrypted state

### ISSUE THREAD

**Issue by schoettler** [maxdeviant/redux-persist-transform-encrypt#4]
I implemented the transform while I had a previously unencrypted state in localstorage, remains unencrypted.

**Comment by maxdeviant** [comment]
Are you sure that a persist actually went through?

Going to need some more actionable information here to help you out.

**Comment by schoettler** [comment]
Works fine actually, had something wrong on my end. Sorry about that

**Comment by maxdeviant** [comment]
No worries!
