### ISSUE TITLE
Verify compatibility with redux-persist v6

### ISSUE THREAD

**Issue by maxdeviant** [maxdeviant/redux-persist-transform-encrypt#41]
`redux-persist` is up to v6 already, so we need to ensure that `redux-persist-transform-encrypt` is still compatible and update any examples for v6.

**Comment by BugHiding** [comment]
![image](https://user-images.githubusercontent.com/6602889/70309597-d34d6c80-1848-11ea-86d5-5776beb10122.png)

![image](https://user-images.githubusercontent.com/6602889/70309789-3d661180-1849-11ea-93fc-69413f290908.png)

```log
```

`@types/redux-persist-transform-encrypt@2.0.1`  persistStore() type has error

**Comment by maxdeviant** [comment]
This should be working now, as evidenced by the [end-to-end test](https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/b96da9a53b88258969806b49b539e43b4730dad7/src/__tests__/e2e.test.ts).
