### ISSUE TITLE
Issues with installing, Unable to resolve module `events` 

### ISSUE THREAD

**Issue by ChrystianSchutz** [maxdeviant/redux-persist-transform-encrypt#42]
I tried to install this library, but sadly i have this error, after trying to install using yarn(1.19.1) or npm(6.9.0). I also tried removing node_modules and cleaning cache.
`error: bundling failed: Error: Unable to resolve module `events` from `C:\graditude\minute-gratitude-journal\node_modules\readable-stream\lib\_stream_readable.js`: Module `events` does not exist in the Haste module map`
Even after cloning it and installing it manually as local package with (events) I have another issues, which is:
Can't find variable Buffer, also I tried to add it to this library package json, but it still fails.
![obraz](https://user-images.githubusercontent.com/3518695/69010194-95ea7300-095d-11ea-8708-fc192b26271a.png)

**Comment by maxdeviant** [comment]
Closing as this does not seem like a problem with `redux-persist-transform-encrypt`.
