### ISSUE TITLE
Cannot save simple text as state.

### ISSUE THREAD

**Issue by mxsxs2** [maxdeviant/redux-persist-transform-encrypt#46]
I have a setup where I have multiple reducers and I only persist a part of the state coming from the reducers. For this I have the `combineReducers` reducers like:
```
combineReducers(
      reducer1: ...some reducer,
      reducer2: persistReducer({
            key: "foo",
            storage: createIdbStorage({ name: "foo", storeName: "foo" })
            transforms: [createEncryptor({
                secretKey: 'mykey',
            }]
        },
       ...some reducer
      )
)
```
Default state:
```
{
 reducer1: {/*some data*/},
 reducer2: {
      bar: {
                 key: "hello"
             },
       my:  "olleh"
     }
}
```

This persisting and ecrypt/decrypt will cause:
```
{
 reducer1: {/*some data*/}, //this is untouched as was never persisted
 reducer2: { 
      bar: {
                 key: "hello" //this works 
             },
       my:  null //returns null as JSON.parse cannot parse plain string
     }
}
```

We could simply add return the decrypted value at [sync.js Line:16](https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/b5f99d637ea724db979c30c138f324776e96f130/src/sync.js#L16) instead if a throw error. But that will remove the way how the correctness of the key is checked.

**Comment by Dylan0916** [comment]
+1😭

**Comment by maxdeviant** [comment]
Plain strings are now supported in v3.0.0, as shown in [this test case](https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/2b3cd240395fdacf038517a7c4697621a851217e/src/__tests__/sync.test.ts#L100-L111).
