### ISSUE TITLE
Error: Unable to resolve module `crypto` 

### ISSUE THREAD

**Issue by ardyfeb** [maxdeviant/redux-persist-transform-encrypt#49]
Got this error on react-native, using `crypto-js@v3.1.9-1` will resolve this error https://github.com/brix/crypto-js/issues/273#issuecomment-602442239 

another solution discussed here https://github.com/brix/crypto-js/pull/259

**Comment by maxdeviant** [comment]
Thanks for the report! This does seem like something that should be fixed.

My guess is that for now we can drop to `crypto-js@v3.1.9-1`.

**Comment by maxdeviant** [comment]
This should be fixed in v3.0.1.
