### ISSUE TITLE
ERROR: (0, _reduxPersistTransformEncrypt.default) is not a function

### ISSUE THREAD

**Issue by sacmii** [maxdeviant/redux-persist-transform-encrypt#50]
ERROR    TypeError: (0, _reduxPersistTransformEncrypt.default) is not a function. (In '(0, _reduxPersistTransformEncrypt.default)({
    secretKey: _LoginPasswordKey.reduxEncrypt,
    onError: function onError(error) {}
  })', '(0, _reduxPersistTransformEncrypt.default)' is undefined)

Package Version: "redux-persist-transform-encrypt": "^3.0.1",

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 432.12 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0 
    react-native: ^0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by maxdeviant** [comment]
We no longer expose a default export. Please use the named export:

```ts
import { encryptTransform } from 'redux-persist-transform-encrypt';
```
