### ISSUE TITLE
Fix failing async test

### ISSUE THREAD

**Issue by maxdeviant** [maxdeviant/redux-persist-transform-encrypt#6]
Currently the tests for the async functionality (added in #5) are failing, as noted in [this comment](https://github.com/maxdeviant/redux-persist-transform-encrypt/pull/5#issuecomment-255589578):

> Also, as you might have noticed, the test for the async way was failing. I've wrapped the stream in a promise that will resolve with the completed string when it's ready. But still the encryption test passes and decryption fails. I think the encryption is passing only due to the test state object being really small and it manages to resolve before expect() starts working.

These should be fixed.

**Comment by sibelius** [comment]
is this still a thing?

**Comment by maxdeviant** [comment]
@sibelius Yes, [this test](https://github.com/maxdeviant/redux-persist-transform-encrypt/blob/master/src/__tests__/async.test.js#L28-L45) is still commented out because it's failing.

I don't think it's the test that's bad but rather we need to take a look at how the async functionality is implemented.

**Comment by maxdeviant** [comment]
Asynchronous support has been removed in #47.
