### ISSUE TITLE
Vitest failing with message - Failed to resolve entry for package "redux-persist-transform-encrypt"

### ISSUE THREAD

**Issue by McGern** [maxdeviant/redux-persist-transform-encrypt#75]
Hi.

Thanks for the wonderful package. I am using Vite it seems to be working fine, but when I run with Vitest, the tests are failing with this message. Not sure what to do, because I don't actually want to encrypt the store in the test, but I can't seem to put in a conditional that will ignore it. I'm using the same setup as the sample e.g.

transform: [
  encryptTransform({
    secretKey
  })
]

Error: Failed to resolve entry for package "redux-persist-transform-encrypt". The package may have incorrect main/module/exports specified in its package.json.
 ❯ packageEntryFailure node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11      
 ❯ resolvePackageEntry node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5       
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20
 ❯ Context.resolveId node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28        
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:46
 ❯ TransformContext.resolve node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23 
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40500:34
 ❯ async file:/C:/projects/digital-patient-experience/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
 ❯ TransformContext.transform node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40577:13
 ❯ Object.transform node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29

Is there some setup/config that I might be missing?

Even if I don't use the transform and just have encryptConfig somewhere in the file not doing anything it still fails.

Thanks very much,
J

**Comment by McGern** [comment]
I have ended up just taking the sync.ts code and adding it directly which seems to work for now.

**Comment by maxdeviant** [comment]
Hey @McGern, what version of `redux-persist-transform-encrypt` are you using? v5?

**Comment by McGern** [comment]
Hi,

Thanks for getting back to me.

It's v5, just installed it today. It's working when I take the file
directly and installed the crypto-js and safe stringify plus supporting
types.

J
