### ISSUE TITLE
Failed to resolve the path 

### ISSUE THREAD

**Issue by vksgautam1986** [maxdeviant/redux-persist-transform-encrypt#77]
Error--
 `redux-persist-transform-encrypt` from file `/Users/netsmartz/Desktop/AgencyMobileApplication/src/config/ConfigureStore.js`, the package `/Users/netsmartz/Desktop/AgencyMobileApplication/node_modules/redux-persist-transform-encrypt/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/netsmartz/Desktop/AgencyMobileApplication/node_modules/redux-persist-transform-encrypt/index`. Indeed, none of these files exist:

Current Version -- 4.0.0 and even with latest 5.0.1. i am having the same issue

**Comment by vksgautam1986** [comment]
i am copying index.js file from lib folder to the level of package json folder . it working for this issue but then i am getting another issue.
 ERROR  redux-persist failed to create sync storage. falling back to noop storage.
 ERROR  Error: Native crypto module could not be used to get secure random number.
const persistConfig = {
    key: "root",
    storage,
    timeout: null,
    blacklist: ['common'],
    transforms: [ encryptTransform({
        secretKey: 'secret key already here',
        onError: function (error) {
          // Handle the error.
        },
      }),],
};

**Comment by chadhobson** [comment]
Change your import to...

`import { encryptTransform } from "redux-persist-transform-encrypt/lib/sync";`

Then I had this for my storage import...

`import storage from 'redux-persist/lib/storage';`

Next, I ditched that in favor of @react-native-community/async-storage@^1.12.1....

`import AsyncStorage from '@react-native-community/async-storage';`

Finally, change out your storage in your persistConfig to just...

`storage: AsyncStorage`

**Comment by vksgautam1986** [comment]
thanks its work fine for me.
