### ISSUE TITLE
EPEERINVALID

### ISSUE THREAD

**Issue by bapjiws** [maxdeviant/redux-persist-transform-encrypt#8]
> npm ERR! peerinvalid The package redux-persist@4.0.0-beta1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-persist-transform-encrypt@0.1.2 wants redux-persist@^3.0

Can you please set redux-persist-transform-encrypt to require the latest version of redux-persist? Thanks a lot in advance!

**Comment by rt2zz** [comment]
will be cutting v4.0.0 very shortly!

**Comment by maxdeviant** [comment]
@rt2zz What would you recommend for peer dependencies?

Should I match against major/minor versions and ignore patches?

e.g. `^4.0.x` or `^4.x.x`?

**Comment by rt2zz** [comment]
I am committed to following semver, so 4.x.x should be best

pretty much 4.0 is held back by https://github.com/rt2zz/redux-persist/pull/236 at this point and confirming that we can make the bundle size smaller without need for any breaking changes.

**Comment by maxdeviant** [comment]
This should be done with [v0.2.0](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v0.2.0).
