### ISSUE TITLE
Module not found issue in react

### ISSUE THREAD

**Issue by nrishav007** [maxdeviant/redux-persist-transform-encrypt#80]
I am facing an error on the latest version. 
The error is Module not found: Error: Default condition should be last one.
Before i was using this import 
import {encryptTransform} from "redux-persist-transform-encrypt";
How to fix this issue?
using latest node version
@maxdeviant

**Comment by shanulhabib** [comment]
I am also facing this issue today @nrishav007 previously I am using redux-persist-transform-encrypt v5.0.1 after I updated the v5.1.0 still facing the same error in "react": "^18.1.0".

**Comment by nrishav007** [comment]
@shanulhabib I will update the solution if I find any except downgrade the version

**Comment by hhamza-2023** [comment]
@shanulhabib @nrishav007 faced same issue in redux-persist-transform-encrypt v5.0.1.
react = v18.1.0
node = v16.20.2

**Comment by hhamza-2023** [comment]
> @hhamza-2023 use the latest node version. in v5.0.1 there is no issue

did your issue resolved?

**Comment by nrishav007** [comment]
@hhamza-2023 not yet. trying

**Comment by nrishav007** [comment]
@shanulhabib @hhamza-2023 I found out the issue exactly but i need some help here. The problem is caused for line number 6. its in the exports object. If you remove the exports object then it will works fine.
  "exports": {
    "default": "./lib/index.js",
    "types": "./lib/index.d.ts"
  },
  we have to do import in different way

**Comment by maxdeviant** [comment]
@nrishav007 Are you using ESM in your project?

**Comment by nrishav007** [comment]
@maxdeviant yes

**Comment by hhamza-2023** [comment]
I faced same issue some files are missing in package. To address the missing files issue in "redux-persist-transform-encrypt," we implemented a custom encryption solution. We created a file named reduxEnc.ts to encapsulate the encryption logic using the crypto-js library. This file exports an EncryptTransform function, which serves as a custom transform for use in Redux Persist.

Here's the content of reduxEnc.ts:
// reduxEnc.ts
import Aes from 'crypto-js/aes.js';
import CryptoJsCore from 'crypto-js/core.js';
import stringify from 'json-stringify-safe';
import { createTransform, Transform } from 'redux-persist';
import type { TransformConfig } from 'redux-persist/lib/createTransform';

const makeError = (message: string) => new Error(`redux-persist-transform-encrypt: ${message}`);

interface EncryptTransformConfig {
  secretKey: string;
  onError?: (err: Error) => void;
}

export const EncryptTransform = (
  config: EncryptTransformConfig,
  transformConfig?: TransformConfig
): Transform<any, any> => {
  // Implementation details...
};

In store.ts, we utilize the EncryptTransform to create an encryption transform for Redux Persist. We configure the persistor with this custom transform and set up the Redux store accordingly.

Here's the relevant part of store.ts:

// store.ts
import { EncryptTransform } from './reduxEnc'; // Update the path accordingly

const encryptor: any = EncryptTransform({
  secretKey: process.env.REACT_APP_PERSIST_SECRET as string,
  onError: function (error: any) {
    console.error('Redux Persist Encryptor Error:', error);
  },
});

const persistConfig = {
  key: 'root',
  storage,
  transforms: [encryptor],
};
const persistedReducer = persistReducer(persistConfig, reducers);

export const store = configureStore({
  reducer: persistedReducer,
  devTools: process.env.REACT_APP_ENVIRONMENT === 'development',
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    }),
});

This custom encryption solution resolves the missing files issue, providing a secure and functional Redux Persist setup for your application.

**Comment by aamiralihussain** [comment]
Thanks @hhamza-2023 it works for me

**Comment by hhamza-2023** [comment]
> Thanks @hhamza-2023 it works for me

You're welcome! I'm glad to hear that it worked for you

**Comment by nrishav007** [comment]
@hhamza-2023 thanks for it
