### ISSUE TITLE
Module not found error when using version 5.1.0

### ISSUE THREAD

**Issue by yoyoyo8x** [maxdeviant/redux-persist-transform-encrypt#81]
I got Module not found: Default condition should be last one error when import encryptTransform. When I downgraded from 5.1.0 to 5.0.1, it worked fine.

**Comment by maxdeviant** [comment]
Could you see if [v5.1.1](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.1.1) fixes your issue?

**Comment by matifriaz** [comment]
It didn't give the expected results. I've created a [Pull Request](https://github.com/maxdeviant/redux-persist-transform-encrypt/pull/82) addressing this issue. Could you kindly review it?

**Comment by sacmii** [comment]
> Could you see if [v5.1.1](https://github.com/maxdeviant/redux-persist-transform-encrypt/releases/tag/v5.1.1) fixes your issue?

<img width="716" alt="Screenshot 2024-01-16 at 11 34 40 AM" src="https://github.com/maxdeviant/redux-persist-transform-encrypt/assets/12546974/d7940238-ab2c-4cf7-bf12-42fdb7ac559b">

Still facing issue in
"redux-persist-transform-encrypt": "^5.1.1"

**Comment by sem4phor** [comment]
Same here. Using metro bundler in an nx react native app

**Comment by maxdeviant** [comment]
If someone could provide a repo with a reproduction of the issue that would be immensely helpful for getting it resolved.

I don't use React Native, `redux-persist`, or `redux-persist-transform-encrypt` anymore, so I don't have anywhere to effectively test any potential fixes.
